### PR TITLE
Update projects.yml

### PR DESCRIPTION
**Pull request by rsaz**
Coloquei em ordem alfabetica pra ficar facil procurar na barra lateral e adicionei a secao framework com o expressots/expressots, framework para server side desenvolvido por brasileiros.

Organized the project list in alphabetical order as well as added the framework section including expressots/expressots which is a server side framework for nodejs developed by Brazilians. 

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/brasil/blob/main/CONTRIBUTING.md>.

### Which change are you proposing?

  - [ ] Adding/updating open source project/s
  - [ ] Adding/updating maintainer/s
  - [x] Add the projects in the page githubbrasil in alphabetical order for easy search, also including a framework section
  
---

### Adding/updating open source project/s

- [x ] The project was built in or receives significant contributions from Brazil
- [ x] The project has at least 100 stargazers

**Why should this open source project be featured?**
The unique server side nodejs typescript framework as an alternative to nestjs. Is being developed by Brazilians for the last 2 years and released 6 months ago, is growing organically without any advertising at the moment.

> Please replace this line with an explanation of why you think these changes should be made.

### Adding/updating maintainer/s

- [ x] Maintainer's location on their GitHub profile indicates as Brazil
- [x ] Maintainer has approved this PR to be included on the website

**What open source project/s does the individual maintain?**

> Please replace this line with GitHub URLs to projects that the individual/s maintains
https://github.com/expressots

### Something that does not neatly fit into the binary options above

- [x] My suggested edits are not about an existing page, or at least not a single one

> Please replace this line with an explanation of your proposed changes.
Add the projects in the page githubbrasil in alphabetical order for easy search, also including a framework section
---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by pachicodes — APPROVED** [review]

**Comment by rsaz** [comment]
Ola @pachicodes , a PR esta dentro do esperado? devo alterar algo? espero que a sugestao proposta seja bem vinda. :)

**Review by pachicodes — APPROVED** [review]

**Comment by pachicodes** [comment]
> Ola @pachicodes , a PR esta dentro do esperado? devo alterar algo? espero que a sugestao proposta seja bem vinda. :)

Tudo certinho! Obrigada pela contribuição 💖

**Comment by rsaz** [comment]
Obrigado @pachicodes. Tem algum outro passo para vermos o projeto na pagina, expressots/expressots?
image

No mais parabens pela iniciativa, se precisar de mantenedor so pedir ajuda que no que eu puder ajudar estou por aqui.

**Pull request merged**
